FROM openjdk:15
ARG JAR_FILE
ARG SPRING_DATA_MONGODB_USER_FINANCE
ARG SPRING_DATA_MONGODB_PASSWORD_FINANCE
ARG SPRING_DATA_MONGODB_DATABASE_FINANCE
ENV SPRING_DATA_MONGODB_USER_FINANCE=${SPRING_DATA_MONGODB_USER_FINANCE}
ENV SPRING_DATA_MONGODB_PASSWORD_FINANCE=${SPRING_DATA_MONGODB_PASSWORD_FINANCE}
ENV SPRING_DATA_MONGODB_DATABASE_FINANCE=${SPRING_DATA_MONGODB_DATABASE_FINANCE}
COPY target/${JAR_FILE} app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]